apiVersion: v1
kind: Service
metadata:
  name: flask-user-manager-service
  namespace: default
  labels:
    app: flask-user-manager
spec:
  type: LoadBalancer
  selector:
    app: flask-user-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
